language: ruby
sudo: false
script: "gem install html-proofer github-pages jekyll-mentions jemoji jekyll-redirect-from jekyll-sitemap && set -e && bundle exec jekyll build && bundle exec htmlproof ./_site"
#rvm: 2.1
notifications:
#    email: false
matrix:
    fast_finish: true
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
