# Trusty beta has everything I need in the mega image.
sudo: required
dist: trusty

language: python
python:
 - "3.5"

# install Java 8 as required by vnu.jar
before_install:
 - sudo apt-get update
 - sudo apt-get install oracle-java8-installer
 - sudo update-java-alternatives -s java-8-oracle
 - gem install github-pages

install:
 - pip install html5validator

script: 
  - jekyll build --drafts --profile
  - html5validator --root _site/ --blacklist r

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  irc:
    channels:
      # To be encrypted if issues arise
      - "ircs://chat.freenode.net:6697/##Mikaela"
    # I would prefer to use notifications, but TeleIRC doesn't direct them.
    use_notice: false
