# Site settings
title: Mikaela's jekyll
description: > # this means to ignore newlines until "baseurl:"
    Mikaela's homepage where she will be trying to learn Jekyll a little.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikaela.info" # the base hostname & protocol for your site
#twitter_username: Mkaysi
#github_username:  Mikaela

# Build settings
markdown: kramdown
input: GFM

# Custom settings
timezone: Europe/Helsinki
encoding: utf-8
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
exclude: [PGP, PHP, keybase.txt]
