# Site settings
title: Mikaela
description: > # this means to ignore newlines until "baseurl:"
    I am a Highly Sensitive Autistic Pirate with Linux experience from 2008. I am familiar with git and unemployed.
    <br/><br/>*This website is licensed under the
    [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)
    by [Mikaela Suomalainen](https://mikaela.info/).*
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mikaela.info" # the base hostname & protocol for your site
#twitter_username: Inaneierase
#github_username:  Mikaela
#facebook_username: mikaelahmsuomalainen

# Build settings
markdown: kramdown
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Europe/Helsinki
encoding: utf-8
plugins:
    - jekyll-feed
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
include: [PGP, PHP, keybase.txt, robots.txt, avatar.jpeg]

avatar: https://cloudflare-ipfs.com/ipfs/QmbRqyJteL8qyYefSMgVBWUEKoXRNQL7q61xhcJeoRr35h/250x250.jpg
icon: https://cloudflare-ipfs.com/ipfs/Qma7jaHDBkGk6aEuJEbbCaqgykUrn1X8XhtZ2nMbrYgVKv/128x128.jpg

# {{site.ipfs}}/IPFSHASHHERE to get ipfs link via gateway. Hopefully future
# proof letting me simply swap the link here instead of changing it
# everywhere in case I will start using it.
# NOTE! I didn't get image embedding working with this, but the theory
# seems sound.
# IMPORTANT! When adding content, either add a directory with
# `ipfs add -r` OR SINGLE FILE `ipfs add -w file` so a new directory gets
# created for the content and when it's used, the filename and type are
# remembered which may be helpful with media files or embeds.
ipfs: https://cloudflare-ipfs.com/ipfs
# IPNS is also a thing
ipns: https://cloudflare-ipfs.com/ipns
