# Site settings
title: Mikaela A͟m͟i͟n͟d͟a͟ H. M. Suomalainen
description: > # this means to ignore newlines until "baseurl:"
    I am a Highly Sensitive Autistic Pirate with Linux experience from 2008. I am familiar with git and looking for employment.
    <br/><br/>*This website is licensed under the
    [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)
    by [Mikaela A͟m͟i͟n͟d͟a͟ H. M. Suomalainen](https://mikaela.info/).*
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mikaela.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#theme: jekyll-theme-midnight
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Europe/Helsinki
encoding: utf-8
plugins:
    - jekyll-feed
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
keep_files: [PGP, PHP, keybase.txt, robots.txt, .well-known, ipfs-files]

# Saving time and nerves from blogging about Matrix
matrixLatestRoomVersion: 9

avatar: https://bafybeian33l6hrvjoapve7dxbghs2ej4zeya2cgoldrqo3tm5id7tj6uey.ipfs.dweb.link/250.jpeg
icon: https://bafybeian33l6hrvjoapve7dxbghs2ej4zeya2cgoldrqo3tm5id7tj6uey.ipfs.dweb.link/128.jpeg

# {{site.ipfsGateway}}/ipfs/IPFSHASHHERE to get ipfs link via gateway.
# Hopefully future proof letting me simply swap the link here instead of
# changing it everywhere.
# IMPORTANT! When adding content, either add a directory with
# `ipfs add -r` OR SINGLE FILE `ipfs add -w file` so a new directory gets
# created for the content and when it's used, the filename and type are
# remembered which may be helpful with media files or embeds.
# Note: no trailing slash after the URL, only https://domain.tld
ipfsGateway: https://gateway.ipfs.io
# I am not sure how to use this, but I want it to exist anyway
#   Remember: `ipfs cid base32 <the usual hash>`
ipfsSubdomainGateway: ipfs.dweb.link
# this should be simple to use
ipnsSubdomainGateway: ipns.dweb.link
