# Site settings
title: Mikaela's Jekyll
description: > # this means to ignore newlines until "baseurl:"
    Insert good description here!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikaela.info" # the base hostname & protocol for your site
#twitter_username: Mkaysi
#github_username:  Mikaela

# Build settings
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Europe/Helsinki
encoding: utf-8
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
include: [PGP, PHP, keybase.txt]
