# Site settings
title: Mikaela
description: > # this means to ignore newlines until "baseurl:"
    Rainbowy (trans/ace) aspie, feminist & Linux user since 2008
    <br/><br/>*This website is licensed under the
    [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)
    by [Mikaela Suomalainen](https://mikaela.info/).*
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mikaela.info" # the base hostname & protocol for your site
twitter_username: Inaneierase
github_username:  Mikaela
facebook_username: mikaelahmsuomalainen

# Build settings
markdown: kramdown
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Europe/Helsinki
encoding: utf-8
gems:
    - jekyll-feed
#    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
include: [PGP, PHP, keybase.txt, robots.txt]
