# Site settings
title: Mikaela's website
description: > # this means to ignore newlines until "baseurl:"
    This site includes my blog, public keys and information on finding me
    at IRC. There are also links to my different profiles and possibly
    more interesting subdomains.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mikaela.info" # the base hostname & protocol for your site
# I prefer my GitHub being looked more than Twitter
#twitter_username: Inaneierase
github_username:  Mikaela
#facebook_username: mikaelahmsuomalainen

# Build settings
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Europe/Helsinki
encoding: utf-8
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        # Even if you can see the existence of these pages here, I don't
        # wish to get search engine attention to them.
        - "/bot.html"
        - "/channel.html"
include: [PGP, PHP, keybase.txt, robots.txt]
