name: HTML5 Validator
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Required will all actions
    - name: Checks HTML5 validity
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: _site/
        blacklist: r or ir
